### ISSUE TITLE
Update the dialogue UI

### ISSUE THREAD

**Issue by wumbus** [vr4vet/vr4vet#228]
## TODO:

- [x] Make a new version of the dialogue UI by using already existing UI elements
- [x] Be able to spawn a number of answer buttons according to the number of answer options in the dialogueTree (up to a maximum number (4 ish?)
- [x] Fix the text scaling on the buttons
- [ ] Fix the lambda hard coded stuff in the button spawner script
- [x] figure out why it is so difficult to click the buttons in the middle
